# keycloak/templates/secret.yaml
{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_DB_PASSWORD: "{{ .Values.secret.stringData.password }}"
  KC_DB_USERNAME: "{{ .Values.secret.stringData.username }}"
{{- end }}
